import { Quicksand } from "next/font/google";
import "./globals.css";

const quick_sand = Quicksand({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${quick_sand.className}`}>
        <div className="w-full min-h-screen bg-[#070707]">{children}</div>
      </body>
    </html>
  );
}
